services:
  - type: web
    name: postgres-listener-fakeweb
    env: python
    buildCommand: ""
    startCommand: python email_listener.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: right_switch
          property: connectionString
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: ALERT_EMAIL
        sync: false
